In [161]:
import pandas as pd

# Path to the HTML file containing the table
html_file_path = 'tabel.html'

# Read the HTML file into a pandas DataFrame
tables = pd.read_html(html_file_path)

# Assuming the table you want is the first one in the file
table_df = tables[0]

# Now you have the table data in a DataFrame, you can manipulate it as needed
print(table_df)

     Logo                   Name  Programs        Looking for  \
0     NaN  ACAD International AB       NaN          MasterPhd
1     NaN          Academic Work       NaN  BachelorMasterPhd
2     NaN               Actemium       NaN  BachelorMasterPhd
3     NaN                   AFRY       NaN     BachelorMaster
4     NaN                 AGREAT       NaN     BachelorMaster
..    ...                    ...       ...                ...
160   NaN              Wellspect       NaN  BachelorMasterPhd
161   NaN                 Worley       NaN  BachelorMasterPhd
162   NaN                    WSP       NaN     BachelorMaster
163   NaN              Xamera XB       NaN     BachelorMaster
164   NaN               Zenseact       NaN  BachelorMasterPhd

                            Offering      Fair Area  Favorites
0              WorkThesisSummer work    PostgÃ¥ngen        NaN
1    WorkSummer workTrainee programs       Multisal        NaN
2    WorkThesisSummer workInternship        Volvo 2        NaN
3         WorkThesisTrainee programs        Volvo 3        NaN
4                               Work        Volvo 2        NaN
..                               ...            ...        ...
160            WorkThesisSummer work        Volvo 2        NaN
161                             Work    LjusgÃ¥rden        NaN
162  WorkThesisSummer workInternship  SB-korridoren        NaN
163                       WorkThesis       Multisal        NaN
164  WorkThesisSummer workInternship       Multisal        NaN

[165 rows x 7 columns]

In [162]:
from bs4 import BeautifulSoup
import pandas as pd

# Sample HTML element
html_element = '<td class="q-td text-left"><div class=""><div class="q-avatar" tags="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" removeable="false" clickable="" style="font-size: 32px;"><div class="q-avatar__content row flex-center overflow-hidden"><img src="/api/v2/image/a.svg" cover=""><!----></div></div><div class="q-avatar" tags="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" removeable="false" clickable="" style="font-size: 32px;"><div class="q-avatar__content row flex-center overflow-hidden"><img src="/api/v2/image/f.svg" cover=""></div></div><div class="q-avatar" tags="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" removeable="false" clickable="" style="font-size: 32px;"><div class="q-avatar__content row flex-center overflow-hidden"><img src="/api/v2/image/m.svg" cover=""><!----></div></div><div class="q-avatar" tags="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" removeable="false" clickable="" style="font-size: 32px;"><div class="q-avatar__content row flex-center overflow-hidden"><img src="/api/v2/image/td.svg" cover=""><!----></div></div><div class="q-avatar" tags="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" removeable="false" clickable="" style="font-size: 32px;"><div class="q-avatar__content row flex-center overflow-hidden"><img src="/api/v2/image/tm.svg" cover=""></div></div><div class="q-avatar" tags="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" removeable="false" clickable="" style="font-size: 32px;"><div class="q-avatar__content row flex-center overflow-hidden"><img src="/api/v2/image/v.svg" cover=""><!----></div></div></div></td>'

# Parse the HTML element
def get_image_names(html_element):
    soup = BeautifulSoup(html_element, 'html.parser')

    # Find all div elements with class 'q-avatar'
    avatar_divs = soup.find_all('div', class_='q-avatar')

    # Extract image names from the src attribute of each img tag
    image_names = []
    for avatar_div in avatar_divs:
        img_tags = avatar_div.find_all('img')
        for img_tag in img_tags:
            image_src = img_tag.get('src')
            image_name = image_src.split('/')[-1].split('.')[0]  # Extract image name from URL
            image_names.append(image_name)
    return image_names

print(get_image_names(html_element))

['a', 'f', 'm', 'td', 'tm', 'v']

In [163]:
from bs4 import BeautifulSoup
programs = []

# Read the HTML file
with open(html_file_path, 'r') as file:
    html_content = file.read()

# Parse the HTML content
soup = BeautifulSoup(html_content, 'html.parser')

# Find all tbody elements
tbodies = soup.find_all('tbody')

# Select the third td for every tr in each tbody
for tbody in tbodies:
    rows = tbody.find_all('tr')
    for row in rows:
        # Check if the row has at least 3 td elements
        if len(row.find_all('td')) >= 3:
            third_td = row.find_all('td')[2]  # Selecting the third td element (index 2)
            programs.append(get_image_names(str(third_td)))  # Print the text content of the third td element
programs

[['a', 'f', 'm', 'td', 'tm', 'v'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'v', 'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'td',
  'tm',
  'v',
  'z'],
 ['d', 'e', 'f', 'it', 'mt', 'tm', 'z'],
 ['ae',
  'bt',
  'd',
  'e',
  'f',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'sjo',
  'td',
  'tm',
  'z'],
 ['d', 'e', 'it', 'z'],
 ['e', 'f', 'i', 'm', 'td', 'tm', 'z'],
 ['bt', 'd', 'e', 'f', 'i', 'it', 'm', 'mt', 'td', 'tm', 'z'],
 ['ae', 'd', 'i', 'it', 'z'],
 ['d', 'e', 'i', 'it', 'm', 'td', 'z'],
 ['d', 'e', 'z'],
 ['bt', 'd', 'e', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'tm', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'it', 'k', 'kf', 'm', 'td', 'tm', 'v', 'z'],
 ['ae', 'bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'tm', 'z'],
 ['v'],
 ['ae', 'd', 'e', 'f', 'i', 'it', 'm', 'sjo', 'td', 'tm', 'z'],
 ['d', 'e', 'f', 'i', 'it', 'm', 'td'],
 ['d', 'f'],
 ['d', 'e', 'f', 'k', 'kf', 'm', 'sjo', 'td', 'v', 'z'],
 ['bt', 'k'],
 ['gs', 'k', 'v', 'z'],
 ['d', 'e', 'f', 'it', 'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['d', 'i', 'it'],
 ['ae', 'bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'tm', 'z'],
 ['e', 'i', 'k', 'm', 'td'],
 ['ae', 'd', 'f', 'i', 'it', 'm', 'sjo', 'td', 'tm'],
 ['d', 'e', 'it', 'm', 'td', 'z'],
 ['bt', 'd', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'tm', 'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['d', 'f', 'it', 'tm'],
 ['e', 'f', 'i', 'm', 'z'],
 ['d', 'e', 'f', 'it', 'tm', 'z'],
 ['ae', 'd', 'f', 'i', 'it', 'td'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'v', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'm', 'mt', 'td', 'v', 'z'],
 ['e', 'it', 'm'],
 ['a', 'e', 'f', 'm', 'td', 'v', 'z'],
 ['ae', 'd', 'e', 'f', 'i', 'it', 'm', 'z'],
 ['ae', 'd', 'e', 'i', 'it', 'm', 'td', 'z'],
 ['ae', 'e', 'f', 'gs', 'i', 'it', 'm', 'tm', 'z'],
 ['a', 'ae', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td'],
 ['ae', 'bt', 'd', 'f', 'i', 'it', 'mt', 'td'],
 ['ae', 'bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'z'],
 ['d', 'e', 'f', 'it', 'tm', 'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['d', 'it', 'td'],
 ['e', 'i', 'm', 'td', 'v', 'z'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'm', 'tm', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'm', 'td', 'tm', 'v', 'z'],
 ['d', 'e', 'm', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'm', 'sjo', 'td', 'tm', 'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'm', 'td', 'tm', 'z'],
 ['d', 'e', 'f', 'gs', 'i', 'it', 'm', 'mt', 'td', 'tm'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'm', 'td', 'z'],
 ['ae',
  'bt',
  'd',
  'e',
  'f',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'td',
  'tm',
  'v',
  'z'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'm', 'td', 'z'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'm', 'tm', 'z'],
 ['d', 'e', 'it', 'm', 'td', 'z'],
 ['d', 'e', 'f', 'it', 'tm'],
 ['f', 'k', 'kf', 'm', 'v'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'm', 'sjo', 'z'],
 ['e', 'f', 'm', 'z'],
 ['d', 'e', 'f', 'it', 'm', 'tm', 'z'],
 ['d', 'f', 'i', 'm', 'td', 'tm', 'z'],
 ['d', 'it'],
 ['d', 'e', 'f', 'it', 'm', 'tm', 'z'],
 ['ae', 'bt', 'd', 'e', 'f', 'gs', 'i', 'k', 'kf', 'm', 'tm', 'v', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'sjo', 'tm', 'v', 'z'],
 ['ae', 'd', 'i', 'it', 'td'],
 ['bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'mt', 'td', 'tm', 'v'],
 ['a', 'ae', 'e', 'f', 'i', 'm', 'td', 'v', 'z'],
 ['ae', 'd', 'i', 'it', 'td', 'tm'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'v', 'z'],
 ['d', 'e', 'f', 'i', 'it', 'm', 'td', 'tm'],
 ['d', 'e', 'f', 'i', 'm', 'td', 'z'],
 ['i', 'm', 'td', 'z'],
 ['d', 'f', 'i', 'it', 'm', 'td', 'tm', 'z'],
 ['bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'tm', 'v', 'z'],
 ['d', 'e', 'f', 'it', 'm', 'td', 'tm', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'm', 'td', 'tm', 'z'],
 ['ae', 'd', 'e', 'f', 'i', 'it', 'm', 'td', 'tm', 'v', 'z'],
 ['d', 'e', 'i', 'it', 'm', 'td', 'z'],
 ['a', 'ae', 'bt', 'd', 'f', 'gs', 'it', 'k', 'kf', 'v'],
 ['bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'tm', 'z'],
 ['d', 'f', 'it', 'tm', 'z'],
 ['a', 'ae', 'd', 'e', 'i', 'it', 'm', 'td', 'v', 'z'],
 ['d', 'e', 'it', 'z'],
 ['ae', 'd', 'e', 'gs', 'it', 'm', 'sjo', 'v', 'z'],
 ['d', 'e', 'f', 'i', 'it', 'm', 'td', 'z'],
 ['e', 'f', 'k', 'kf', 'm', 'sjo', 'z'],
 ['d', 'e', 'f', 'it', 'tm', 'z'],
 ['ae', 'd', 'i', 'it', 'm'],
 ['ae', 'bt', 'd', 'e', 'f', 'gs', 'it', 'k', 'kf', 'mt', 'td'],
 ['d', 'e', 'f', 'm', 'tm', 'v'],
 ['ae', 'e', 'i', 'k', 'm', 'z'],
 ['d', 'e', 'f', 'it', 'm', 'td', 'tm', 'z'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'm', 'td', 'z'],
 ['e', 'f', 'i', 'k', 'kf', 'm', 'mt', 'tm', 'z'],
 ['a', 'e', 'm', 'v', 'z'],
 ['ae', 'f', 'i', 'm', 'td', 'tm', 'v'],
 ['ae', 'd', 'i', 'it', 'td', 'tm'],
 ['bt', 'e', 'f', 'i', 'k', 'kf', 'm', 'td', 'z'],
 ['d', 'e', 'f', 'it', 'm', 'td', 'tm', 'z'],
 ['d', 'f', 'i', 'it', 'm', 'tm', 'z'],
 ['d', 'e', 'i', 'it', 'm', 'td', 'tm', 'z'],
 ['bt', 'f', 'k', 'kf', 'm'],
 ['ae', 'e', 'i', 'sjo', 'v'],
 ['e', 'f', 'i', 'k', 'kf', 'm', 'td', 'z'],
 ['ae', 'bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'sjo', 'td', 'v', 'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'it', 'mt', 'td', 'tm', 'v', 'z'],
 ['d', 'it'],
 ['ae', 'd', 'f', 'i', 'it', 'tm', 'z'],
 ['bt', 'f', 'k', 'kf', 'mt'],
 ['e', 'f', 'it', 'm', 'mt', 'td', 'tm', 'z'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'z'],
 ['a',
  'bt',
  'd',
  'e',
  'f',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'td',
  'tm',
  'v',
  'z'],
 ['ae', 'd', 'e', 'f', 'i', 'it', 'm', 'td', 'tm', 'z'],
 ['d', 'e', 'f', 'gs', 'i', 'it', 'td', 'z'],
 ['ae', 'd', 'e', 'i', 'k', 'kf', 'm', 'mt', 'sjo', 'v', 'z'],
 ['bt', 'f', 'k', 'kf', 'm'],
 ['d', 'e', 'f', 'it', 'm', 'sjo', 'tm', 'v', 'z'],
 ['bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'z'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'sjo', 'td', 'z'],
 ['ae', 'bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'z'],
 ['d', 'e', 'i', 'it', 'm', 'td', 'tm', 'z'],
 ['d', 'f', 'it', 'td', 'tm'],
 ['d', 'it', 'tm'],
 ['bt', 'k', 'm', 'sjo', 'z'],
 ['a', 'ae', 'd', 'e', 'i', 'it', 'sjo', 'td', 'tm', 'v', 'z'],
 ['ae', 'bt', 'd', 'e', 'f', 'gs', 'i', 'k', 'kf', 'm', 'td', 'z'],
 ['ae', 'f', 'i', 'it', 'k', 'm', 'td', 'tm'],
 ['e', 'm', 'v'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['a', 'v'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'td', 'z'],
 ['d', 'e', 'i', 'it', 'm', 'z'],
 ['d', 'e', 'f', 'it', 'tm'],
 ['ae', 'd', 'e', 'f', 'i', 'it', 'm', 'mt', 'td', 'tm', 'z'],
 ['bt', 'e', 'f', 'i', 'k', 'kf', 'm', 'td', 'tm', 'v', 'z'],
 ['d', 'e', 'it', 'z'],
 ['ae', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'sjo', 'td', 'v', 'z'],
 ['ae', 'bt', 'd', 'e', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'z'],
 ['e', 'i', 'it', 'm', 'td', 'z'],
 ['a', 'ae', 'td', 'v'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'td'],
 ['it', 'td', 'z'],
 ['a', 'ae', 'd', 'e', 'f', 'it', 'k', 'kf', 'm', 'sjo', 'td', 'tm', 'v'],
 ['d', 'f', 'i', 'it', 'm', 'sjo', 'td', 'v', 'z'],
 ['ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['a',
  'ae',
  'bt',
  'd',
  'e',
  'f',
  'gs',
  'i',
  'it',
  'k',
  'kf',
  'm',
  'mt',
  'sjo',
  'td',
  'tm',
  'v',
  'z'],
 ['ae', 'd', 'e', 'f', 'gs', 'i', 'it', 'k', 'kf', 'm', 'tm', 'v'],
 ['d', 'it'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'td', 'v'],
 ['d', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'td', 'tm', 'z'],
 ['a', 'bt', 'd', 'e', 'it', 'mt', 'v'],
 ['d', 'it'],
 ['ae', 'bt', 'd', 'e', 'f', 'i', 'it', 'k', 'kf', 'm', 'mt', 'td', 'z'],
 ['e', 'f', 'k', 'kf', 'm', 'v', 'z'],
 ['a', 'e', 'v', 'z'],
 ['d', 'e', 'f', 'it', 'm', 'mt', 'sjo', 'tm', 'z'],
 ['d', 'e', 'f', 'it', 'k', 'kf', 'm', 'td', 'tm', 'z']]

In [164]:
table_df["Programs"] = programs
table_df = table_df.drop(columns=['Logo', 'Favorites'], axis=1)
table_df

,Name,Programs,Looking for,Offering,Fair Area
0,ACAD International AB,"[a, f, m, td, tm, v]",MasterPhd,WorkThesisSummer work,PostgÃ¥ngen
1,Academic Work,"[a, ae, bt, d, e, f, gs, i, it, k, kf, m, mt, ...",BachelorMasterPhd,WorkSummer workTrainee programs,Multisal
2,Actemium,"[d, e, f, i, it, k, kf, m, td, tm, v, z]",BachelorMasterPhd,WorkThesisSummer workInternship,Volvo 2
3,AFRY,"[a, ae, bt, d, e, f, i, it, k, kf, m, mt, td, ...",BachelorMaster,WorkThesisTrainee programs,Volvo 3
4,AGREAT,"[d, e, f, it, mt, tm, z]",BachelorMaster,Work,Volvo 2
...,...,...,...,...,...
160,Wellspect,"[ae, bt, d, e, f, i, it, k, kf, m, mt, td, z]",BachelorMasterPhd,WorkThesisSummer work,Volvo 2
161,Worley,"[e, f, k, kf, m, v, z]",BachelorMasterPhd,Work,LjusgÃ¥rden
162,WSP,"[a, e, v, z]",BachelorMaster,WorkThesisSummer workInternship,SB-korridoren
163,Xamera XB,"[d, e, f, it, m, mt, sjo, tm, z]",BachelorMaster,WorkThesis,Multisal
164,Zenseact,"[d, e, f, it, k, kf, m, td, tm, z]",BachelorMasterPhd,WorkThesisSummer workInternship,Multisal

In [165]:
table_df

,Name,Programs,Looking for,Offering,Fair Area
0,ACAD International AB,"[a, f, m, td, tm, v]",MasterPhd,WorkThesisSummer work,PostgÃ¥ngen
1,Academic Work,"[a, ae, bt, d, e, f, gs, i, it, k, kf, m, mt, ...",BachelorMasterPhd,WorkSummer workTrainee programs,Multisal
2,Actemium,"[d, e, f, i, it, k, kf, m, td, tm, v, z]",BachelorMasterPhd,WorkThesisSummer workInternship,Volvo 2
3,AFRY,"[a, ae, bt, d, e, f, i, it, k, kf, m, mt, td, ...",BachelorMaster,WorkThesisTrainee programs,Volvo 3
4,AGREAT,"[d, e, f, it, mt, tm, z]",BachelorMaster,Work,Volvo 2
...,...,...,...,...,...
160,Wellspect,"[ae, bt, d, e, f, i, it, k, kf, m, mt, td, z]",BachelorMasterPhd,WorkThesisSummer work,Volvo 2
161,Worley,"[e, f, k, kf, m, v, z]",BachelorMasterPhd,Work,LjusgÃ¥rden
162,WSP,"[a, e, v, z]",BachelorMaster,WorkThesisSummer workInternship,SB-korridoren
163,Xamera XB,"[d, e, f, it, m, mt, sjo, tm, z]",BachelorMaster,WorkThesis,Multisal
164,Zenseact,"[d, e, f, it, k, kf, m, td, tm, z]",BachelorMasterPhd,WorkThesisSummer workInternship,Multisal

In [166]:
import re
[type(s) == str for s in list(table_df["Offering"])].index(False)

46

In [167]:
import math
str(table_df.iloc[46]["Offering"]) == "nan"

True

In [168]:
import re
table_df["Looking for"] = [re.findall('[A-Z][^A-Z]*', s) for s in table_df["Looking for"]]
offerings = []
for s in table_df["Offering"]:
    if str(s) == "nan":
        offerings.append([])
        continue
    offerings.append(re.findall('[A-Z][^A-Z]*', s) )
table_df["Offering"] = offerings

In [169]:
table_df

,Name,Programs,Looking for,Offering,Fair Area
0,ACAD International AB,"[a, f, m, td, tm, v]","[Master, Phd]","[Work, Thesis, Summer work]",PostgÃ¥ngen
1,Academic Work,"[a, ae, bt, d, e, f, gs, i, it, k, kf, m, mt, ...","[Bachelor, Master, Phd]","[Work, Summer work, Trainee programs]",Multisal
2,Actemium,"[d, e, f, i, it, k, kf, m, td, tm, v, z]","[Bachelor, Master, Phd]","[Work, Thesis, Summer work, Internship]",Volvo 2
3,AFRY,"[a, ae, bt, d, e, f, i, it, k, kf, m, mt, td, ...","[Bachelor, Master]","[Work, Thesis, Trainee programs]",Volvo 3
4,AGREAT,"[d, e, f, it, mt, tm, z]","[Bachelor, Master]",[Work],Volvo 2
...,...,...,...,...,...
160,Wellspect,"[ae, bt, d, e, f, i, it, k, kf, m, mt, td, z]","[Bachelor, Master, Phd]","[Work, Thesis, Summer work]",Volvo 2
161,Worley,"[e, f, k, kf, m, v, z]","[Bachelor, Master, Phd]",[Work],LjusgÃ¥rden
162,WSP,"[a, e, v, z]","[Bachelor, Master]","[Work, Thesis, Summer work, Internship]",SB-korridoren
163,Xamera XB,"[d, e, f, it, m, mt, sjo, tm, z]","[Bachelor, Master]","[Work, Thesis]",Multisal
164,Zenseact,"[d, e, f, it, k, kf, m, td, tm, z]","[Bachelor, Master, Phd]","[Work, Thesis, Summer work, Internship]",Multisal

In [170]:
bool(set(table_df.iloc[1]["Programs"]) & set(programs))

TypeError: unhashable type: 'list'

In [ ]:
bool(set(list(table_df.iloc[0]["Programs"])) & set(programs))

False

In [172]:
def find_company(table_df, programs, program_level, offering_types):
    good_companies = []
    for i in range(table_df.shape[0]):
        company = table_df.iloc[i]
        a = bool(set((company["Programs"])) & set(programs))
        a = a and bool(set(list(company["Looking for"])) & set(program_level))
        a = a and bool(set(list(company["Offering"])) & set(offering_types))
        if a:
            good_companies.append(company["Name"])
    return good_companies

programs = ["d", "it"]
program_level = ["Bachelor", "Master"]
offering_types = ["Summer work"]

find_company(table_df, programs, program_level, offering_types)

['Academic Work',
 'Actemium',
 'Alfa Laval',
 'ALIARO',
 'AstraZeneca',
 'Aurobay',
 'Berg Propulsion',
 'Beyond Gravity',
 'Boeing',
 'Borealis AB',
 'Centiro',
 'CEVT',
 'Cloud Software Group',
 'Consilium Safety Group',
 'CPAC Systems AB',
 'CTC',
 'Dana TM4',
 'Dentsply Sirona',
 'Easy-Laser AB',
 'Einride',
 'Emerson',
 'Engineers Without Borders',
 'Epiroc',
 'Ericsson',
 'Essity Hygiene & Health AB',
 'GE Additive',
 'Gryaab AB',
 'GÃ¶teborg Energi AB',
 'Hitachi Enegy',
 'Huawei Technologies Sweden AB',
 'Husqvarna Group',
 'Industrial Path Solutions Sweden AB',
 'INEOS Inovyn',
 'Kollmorgen Automation AB',
 'LumenRadio',
 'Magna Electronics Sweden',
 'MÃ¶lnlycke Health Care',
 'Ongoing',
 'Preem',
 'Qualcomm',
 'RaySafe',
 'Saab AB',
 'Satcube',
 'SCA',
 'SKF',
 'Skill',
 'SLB',
 'Stena AB',
 'Sweco Sverige AB',
 'Swedish Match',
 'T-engineering AB',
 'Tetra Pak',
 'Thermia',
 'Thorlabs Sweden',
 'Trafikverket',
 'Transportstyrelsen',
 'Vattenfall AB',
 'Volvo Cars',
 'Volvo Group',
 'VÃ¤stra GÃ¶talandsregionen',
 'Wellspect',
 'Zenseact']